### ISSUE TITLE
Allow choosing version

### ISSUE THREAD

**Issue by cypherdare** [sky-uk/gradle-maven-plugin#1]
It would be nice if you could set a string property to select a specific commit from this repository instead of the latest commit from master. [These lines](https://github.com/sky-uk/gradle-maven-plugin/blob/07b1b846ba4d023df50acf283edd51f3b201dc28/gradle-mavenizer.gradle#L3) could use the string property if it exists but default to "master" if it doesn't.

I know this doesn't matter yet, but if there are future changes that cause behavior changes, I'd prefer to opt-in to new changes.

**Comment by gotev** [comment]
@cypherdare do you have any proposal about how we should implement this? 😉

**Comment by cypherdare** [comment]
I'll take a stab at it this weekend, thanks.

**Comment by gotev** [comment]
Available starting from `1.0.3`
