### ISSUE TITLE
Have full Doc ?

### ISSUE THREAD

**Issue by CMingTseng** [sky-uk/gradle-maven-plugin#15]
Dear Sir 

Sorry for my poor English & knowledge

Do you can create a full Android Demo Project ?

THX

**Comment by TUBB** [comment]
Hello
You can look at this [project](https://github.com/TUBB/FriendlyCrash) for some use cases.
Hope this helps.

**Comment by gotev** [comment]
Check also this project which has many modules: https://github.com/gotev/android-upload-service/
