### ISSUE TITLE
Problem with BOM DependencyManager

### ISSUE THREAD

**Issue by DanteNguyen1008** [sky-uk/gradle-maven-plugin#17]
I am not using the plugin now but I have same decoratePOM code. It does not work if I use [dependencyManagement](https://docs.gradle.org/5.0/userguide/managing_transitive_dependencies.html#sec:bom_import) in Gradle 5x. 

ext.addDependencies is empty so it does not add any to POM file's <dependencies>.

Have you ever try to use them together?

**Comment by Fed93** [comment]
Never tried, but I'll do some research to understand how it works and how to insert in gradle-maven-plugin.

**Comment by DanteNguyen1008** [comment]
I ended up replacing BOM dependency management from Gradle 5 with this [spring plugin ](https://github.com/spring-gradle-plugins/dependency-management-plugin) and generating the POM file my self.
