### ISSUE TITLE
Received status code 405 from server: Method Not Allowed

### ISSUE THREAD

**Issue by 123lxw123** [sky-uk/gradle-maven-plugin#18]
Configuration: 
```
project.ext {
    mavDevelopers = ["ME":"Developers"]
    mavSiteUrl = "https://aria2.kezaihui.com/ME/android_lib"
    mavGitUrl = "git@aria2.kezaihui.com:ME/android_lib.git"
    mavProjectName = 'ZaihuiLib'
    mavLibraryLicenses = ["Apache-2.0":'http://www.apache.org/licenses/LICENSE-2.0.txt']
    mavLibraryDescription = "Android lib for Zaihui App"
    mavPublishToRemoteRepo = true
    mavRemoteRepoUser = MAVEN_USER
    mavRemoteRepoPassword = MAVEN_PASSWORD
    mavRepoRemoteUrl = MAVEN_URL
}
```
MAVEN_URL is "https://dl.bintray.com/zaihuime/maven/", I got this error message. May be I should change the HTTP Method PUT to POST, but I don't know how I can do it. Any help? Thanks.
****
> Task :lib-android:publishMavenPublishPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lib-android:publishMavenPublishPublicationToMavenRepository'.
> Failed to publish publication 'mavenPublish' to repository 'maven'
   > Could not write to resource 'https://dl.bintray.com/zaihuime/maven/com/zaihui/lib-android/1.0.0/lib-android-1.0.0.aar'.
      > Could not PUT 'https://dl.bintray.com/zaihuime/maven/com/zaihui/lib-android/1.0.0/lib-android-1.0.0.aar'. Received status code 405 from server: Method Not Allowed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by Fed93** [comment]
@123lxw123 in order to upload your library to Bintray you have to use bintray gradle plugin instead of gradle-maven-plugin.
You can check out documentation about Bintray Gradle Plugin [here](https://github.com/bintray/gradle-bintray-plugin)

**Comment by 123lxw123** [comment]
@Fed93 Thanks for your response! It saved my days!
