### ISSUE TITLE
pom.xml

### ISSUE THREAD

**Issue by Guiorgy** [sky-uk/gradle-maven-plugin#2]
How do I generate a pom.xml?

**Comment by gotev** [comment]
Can you please explain what you expect with more details?

**Comment by Guiorgy** [comment]
would it be possible for the plugin to expose the pom as a string?
example:
```java
task createPom {
    apply plugin: 'com.github.dcendents.android-maven'
    pom {
        project {
            packaging 'aar'
        }
    }.writeTo("$buildDir/pom.xml")
}
```

**Comment by Fed93** [comment]
You can run the project task `generatePomFileForMavenPublishPublication` from Command-Line or Gradle menu in your IDE.
You can also run the command for only a module of your library from Command-Line using
```./gradlew moduleName:generatePomFileForMavenPublishPublication``` or from Gradle menu.

Pom file will be saved in ```build/publications/mavenPublish/``` as ```pom-default.xml```
