### ISSUE TITLE
ERROR: Could not get unknown property 'libraryVariants' for object of type com.android.build.gradle.internal.dsl.BaseAppModuleExtension.

### ISSUE THREAD

**Issue by gabriel-TheCode** [sky-uk/gradle-maven-plugin#21]
![variantLlibrary error](https://user-images.githubusercontent.com/26333609/62641189-fe778c00-b93a-11e9-9407-e19c2755e3ae.PNG)

![variantLlibrary error2](https://user-images.githubusercontent.com/26333609/62641923-8dd16f00-b93c-11e9-9362-e3edc4d5435d.PNG)

When I add the line below
`apply from: 'https://raw.githubusercontent.com/sky-uk/gradle-maven-plugin/master/gradle-mavenizer.gradle'`    I have the error on the image. 

Need Help please !

Platform: 
- Android 3.4.2
- Gradle 5.1.1
- API Version 28

**Comment by Fed93** [comment]
@gabriel-TheCode can you please share your build.gradle files? 
If you have multiple modules please share their gradle file and the project root build.gradle.

**Comment by gabriel-TheCode** [comment]
I solved this problem by migrating the project to Androidx and using  `classpath 'com.github.dcendents:android-maven-gradle-plugin:2.1'`

I still don't know where the problem came from but I think it was definitely a problem due to a conflict between android.support* and androidx libraries.

**Comment by pcchin** [comment]
I also encountered the same problem, however my project has already been migrated to AndroidX. 
Platform:
* Android Studio 3.6.2
* Gradle 5.6.4
* API Version 29

Info:
* root/build.gradle: [Pastebin Link](https://pastebin.com/dWiR1xE0)
* app/build.gradle: [Pastebin Link](https://pastebin.com/u8B0vT9h)
* Gradle output (with --debug): [Pastebin Link](https://pastebin.com/b0KungFD)
