### ISSUE TITLE
unable to resolve project version for andorid library

### ISSUE THREAD

**Issue by hereisderek** [sky-uk/gradle-maven-plugin#22]
![image](https://user-images.githubusercontent.com/839795/62994678-45bcca00-beb1-11e9-854c-ede0b487200e.png)

see this commit: https://github.com/hereisderek/android-util/tree/dc3455a

module build.gradle file:

```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'maven-publish'


android {
    compileSdkVersion 29
    buildToolsVersion "29.0.1"



    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 2
        versionName "0.1.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    kotlinOptions {
        freeCompilerArgs = ["-XXLanguage:+InlineClasses"]
    }

    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }


}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'com.jakewharton.timber:timber:4.7.1'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.core:core-ktx:1.0.2'

    implementation 'androidx.viewpager2:viewpager2:1.0.0-beta03'

    implementation ("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.2")
    implementation ("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.2.2")
    implementation ("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.2-1.3.50-eap-5")


    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}

project.ext {
    mavSiteUrl = "https://github.com/hereisderek/android-util"
    mavGitUrl = mavSiteUrl + '.git'
    mavProjectName = 'android-util'
    mavPublishToMavenLocal = true
    mavLibraryLicenses = ["Apache-2.0":'http://www.apache.org/licenses/LICENSE-2.0.txt']
    mavLibraryDescription = "A collection of android utilies"
}

apply from: 'https://raw.githubusercontent.com/sky-uk/gradle-maven-plugin/master/gradle-mavenizer.gradle'

```

**Comment by hereisderek** [comment]
update: 
I added a line in the module's build.gradle file, right above `apply from: 'https://raw.githubusercontent.com/sky-uk/gradle-maven-plugin/master/gradle-mavenizer.gradle'`

`version = android.defaultConfig.versionName` 

now the version can be picked up by the plugin.

however, should we make this process automatic/enablable, by providing a flag in the config block  (such as `mavUseAndroidVersion` etc.)

**Comment by hereisderek** [comment]
actually, I'll just open this issue so the author can notice it.

feel free to close it afterward tho.

**Comment by Fed93** [comment]
@hereisderek you must set a `version` value in the build.gradle file for a correct configuration of your library, not just for the `maven-gradle-plugin`.
For your suggestion to add a new param of the plugin configuration, the `version` param is used internally by gradle and by the gradle plugin and i think it's incorrect to not set it.

**Comment by hereisderek** [comment]
> @hereisderek you must set a `version` value in the build.gradle file for a correct configuration of your library, not just for the `maven-gradle-plugin`.
> For your suggestion to add a new param of the plugin configuration, the `version` param is used internally by gradle and by the gradle plugin and i think it's incorrect to not set it.

with limited knowledge I have regarding gradle, it seems odd to me having two different versions for an android library ("project.version" vs "android.defaultConfig.versionName") 

since we are checking if it was an android library internally, maybe we can use android version if project version is not set as a fall back?

Anyway, I'll just use `version` for now and close this issue
