### ISSUE TITLE
Upload to Bintray?

### ISSUE THREAD

**Issue by Myk-da-Beast** [sky-uk/gradle-maven-plugin#28]
I want to upload to Bintray, can this plugin do that? I see the `mavRemoteRepo` is that what I need to use? If so do I give it the username and password to my bintray account? And what Url do I pass?

**Comment by Fed93** [comment]
@Myk-da-Beast in order to upload your library to Bintray you have to use bintray gradle plugin instead of gradle-maven-plugin.
Duplicate of #18

**Comment by gotev** [comment]
closing as bintray is sunsetting
