### ISSUE TITLE
Could not get unknown property 'sourceSets' for task ':sourcesJar' 

### ISSUE THREAD

**Issue by ligi** [sky-uk/gradle-maven-plugin#31]
I am seeing the following error when trying this:

 > Could not get unknown property 'sourceSets' for task ':sourcesJar' of type org.gradle.api.tasks.bundling.Jar.

when running gradle-install

you can reproduce it in this branch:
https://github.com/komputing/KEthereum/tree/add_android

**Comment by roliveiravictor** [comment]
Up, same here. Unfortunately with private repo.

**Comment by LionZXY** [comment]
Any update?

**Comment by gotev** [comment]
this should be solved with #33
