### ISSUE TITLE
Kotlin sources are not published for Java libraries

### ISSUE THREAD

**Issue by aleksaboskov** [sky-uk/gradle-maven-plugin#32]
When publishing a pure Java/Kotlin (non-Android) library, Kotlin sources are not included in the sources jar.

It is caused by [this line](https://github.com/sky-uk/gradle-maven-plugin/blob/master/artifact-javadoc-handler.gradle#L41), which only includes Java sources.

[This StackOverflow post](https://stackoverflow.com/questions/11474729/how-to-build-sources-jar-with-gradle/11475089) describes how to include Kotlin sources as well.

**Comment by vincent-paing** [comment]
Any updates on this issue?
