### ISSUE TITLE
Is there a way to publish debug variant?

### ISSUE THREAD

**Issue by rpattabi** [sky-uk/gradle-maven-plugin#35]
I use this plugin to publish my library to local maven. `./gradlew publish` builds release variant and publishes it. At times, I would like to have debug variant published instead of release. This is useful for debugging purchase (particularly C++).

I couldn't find a way gradle-maven-plugin provides to choose the variant to publish. If there is a way, please let me know. If not, please consider adding an option to choose the variant to publish.

**Comment by rpattabi** [comment]
Any help?

**Comment by gotev** [comment]
should be fixed with #30
