### ISSUE TITLE
422 from server: Unprocessable Entity when trying to publish

### ISSUE THREAD

**Issue by rjain90** [sky-uk/gradle-maven-plugin#4]
Execution failed for task ':imagekit:publishMavenPublishPublicationToMavenRepository'.
> Failed to publish publication 'mavenPublish' to repository 'maven'
   > Could not write to resource 'https://github.com/imagekit-developer/imagekit-android/ImageKit/imagekit/unspecified/imagekit-unspecified.aar'.
      > Could not PUT 'https://github.com/imagekit-developer/imagekit-android/ImageKit/imagekit/unspecified/imagekit-unspecified.aar'. Received status code 422 from server: Unprocessable Entity

project.ext {
    mavSiteUrl = "https://imagekit.io/"
    mavGitUrl = "https://github.com/imagekit-developer/imagekit-android.git"
    mavProjectName = 'ImageKit'
    mavPublishToRemoteRepo = true
    mavRemoteRepoUser = "rjain90"
    mavRemoteRepoPassword = "mzoq0987"
    mavRepoRemoteUrl = "https://github.com/imagekit-developer/imagekit-android.git"
    mavLibraryLicenses = ["Apache-2.0":'http://www.apache.org/licenses/LICENSE-2.0.txt']
    mavLibraryDescription = "ImageKit android SDK"
    mavVersion = "1.0"
}

**Comment by gotev** [comment]
Double check your root and module build.gradle, because there's something missing. When you see `unspecified` it means some variable is not properly passed where needed

**Comment by rjain90** [comment]
> Double check your root and module build.gradle, because there's something missing. When you see `unspecified` it means some variable is not properly passed where needed.
@gotev I have checked and double checked for any missing variables but can't find any. I'd really appreciate it if you can look at the project.ext block below and tell me what's missing.
project.ext {
mavSiteUrl = "https://imagekit.io/"
mavGitUrl = "https://github.com/imagekit-developer/imagekit-android.git"
mavProjectName = 'ImageKit'
mavPublishToRemoteRepo = true
mavRemoteRepoUser = "rjain90"
mavRemoteRepoPassword = "mzoq0987"
mavRepoRemoteUrl = "https://github.com/imagekit-developer/imagekit-android.git"
mavLibraryLicenses = ["Apache-2.0":'http://www.apache.org/licenses/LICENSE-2.0.txt']
mavLibraryDescription = "ImageKit android SDK"
mavVersion = "1.0"
}

> Another thing is that you can't use git repository as a maven repository like that. To use GitHub repository as maven repo you have to clone it on your computer and then instruct the maven deployer to deploy to your local `file:///path/to/cloned/repo`. Then you have to git commit and push. Two operations which cannot be and are not supposed to be made by the Gradle maven plugin.
@gotev I'm not sure I understood this. Right now I have an android project with a sample and a library module. I have done all gradle-maven-plugin related changes in the library module's build.gradle. Now I'm trying to publish. Isn't that how it's supposed to be done?

**Comment by gotev** [comment]
The point is that you cannot use a git repository as a maven repository like you are trying to do. Follow this tutorial: https://dzone.com/articles/using-github-as-maven-repository

**Comment by rjain90** [comment]
I'll have look at the tutorial. Thanks a lot for the help.

**Comment by NavjotGT** [comment]
@gotev I am facing the same **unspecified** issue.

Config:

```
project.ext {
    mavDevelopers = ["nav":"nnnaaavvv"]
    mavSiteUrl = "https://github.com/xyz/sdk"
    mavGitUrl = mavSiteUrl + '.git'
    mavProjectName = 'sdk'
    mavPublishToInternalRepo = false
    mavRepoInternalUrl = "/Users/nnnaaavvv/Work/XYZ/SDK/android"

    mavLibraryLicenses = ["SDK License by XYZ"]
    mavLibraryDescription = "SDK License Terms and Conditions by XYZ"

    mavPublishToRemoteRepo = true
    mavRepoRemoteUrl = "https://nav0812.bintray.com/lsdk"
    mavRemoteRepoUser = "nnnaaavvv"
    mavRemoteRepoPassword = "********************"
}
```

Error:

```
> Task :locationsdk:publishMavenPublishPublicationToMavenRepository FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sdk:publishMavenPublishPublicationToMavenRepository'.
> Failed to publish publication 'mavenPublish' to repository 'maven'
   > Could not PUT 'https://nav0812.bintray.com/lsdk/sdk_android/sdk/unspecified/sdk-unspecified.aar'. Received status code 405 from server: Method Not Allowed
```

**Comment by Fed93** [comment]
@NavjotGT in order to upload your library to Bintray you have to use bintray gradle plugin instead of gradle-maven-plugin.
Duplicate of #18
