### ISSUE TITLE
Purpose of the plugin

### ISSUE THREAD

**Issue by thekirankumar** [sky-uk/gradle-maven-plugin#7]
Whats the difference between using this plugin and what's described here https://docs.gradle.org/current/userguide/publishing_maven.html ?

**Comment by Fed93** [comment]
The main difference is in the pom file generation.
Our plugin will generate the pom with all the dependencies of you library (Android or Java) without effort for the developer who uses it.
Also our plugin automatically generate Javadocs and sources files.
In general will simplify the use of maven-publish Gradle plugin; with a few line of code for the configuration you can deploy your library without study how work the maven-publish Gradle plugin.
